language: php
php:
- 7.0
addons:
  ssh_known_hosts: eduforum.online
before_script:
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
- php artisan key:generate
script:
- vendor/bin/phpunit
before_install:
- openssl aes-256-cbc -K $encrypted_55286a5d4eb4_key -iv $encrypted_55286a5d4eb4_iv
  -in deploys.enc -out deploys -d
after_success:
  - bash deploy.sh