language: php
php:
- 7.0
addons:
  ssh_known_hosts: 107.170.53.95
before_script:
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
- php artisan key:generate
script:
- vendor/bin/phpunit
before_install:
- openssl aes-256-cbc -K $encrypted_bb3964dbe7be_key -iv $encrypted_bb3964dbe7be_iv
  -in id_rsanew.enc -out /tmp/id_rsanew -d

before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsanew
- ssh-add /tmp/id_rsanew
after_success:
- git remote add deploying git@107.170.53.95:/var/repo/site.git
- git push deploying
