language: php
php:
- 7.0
addons:
  ssh_known_hosts: eduforum.online
before_script:
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
- php artisan key:generate
script:
- vendor/bin/phpunit

before_install:
- openssl aes-256-cbc -K $encrypted_55286a5d4eb4_key -iv $encrypted_55286a5d4eb4_iv
  -in deploys.enc -out deploys -d

before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploys
- ssh-add /tmp/deploys

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/eduforum deploy@107.170.53.95:/var/repo/site.git
  on:
    branch: master


